Enable override of Tracing editor
IETS3/iets3.opensource pull request #1005
Opened 2024-07-10 16:05 UTC by mgronover

This Ticket addresses: https://github.com/JetBrains/MPS-extensions/issues/855

A ConditionalEditor by default has the hints `conditionalEditor` and `conditionalEditor_doNotUseThisHint`. These hints are enabled by default when the plugin becomes initialized.
If someone wants to overload a conditionalEditor it is not enough to just give it a higher priority. The priority just defines the order of the applied editors (a conditionalEditor might use "[NextEditor](http://127.0.0.1:63320/node?ref=r%3A8d20232d-87e2-425b-b4d7-a9790e401b85%28de.slisson.mps.conditionalEditor.structure%29%2F2877762237607058140)" (s. screenshot on the mps-extension ticket above). So these can be cascaded somehow.

To enable overloading:
Generally an implementation of a conditional editor should also get an new defined editor hint if this editor should be able to be overloadable. The editor implementation that overloads that one must disable that and enable its own editor hint. 

For the Tracing editor this is done here.

2024-07-11 10:36 UTC, mgronover commented
See also the issue #974 and the according PR: #980

2024-07-15 06:50 UTC, arimer requested changes
Thanks for the invetigation and the changes. 👍🏼 
- The implementation looks fine and I like the idea in setting the editor on startup of the plugin. 
- I cleaned up some deps and updated the build

However we should definitively document that change in the changelog before merging. Could you please update it?

2024-07-15 06:52 UTC, arimer commented
@mgronover we should also think about about updating our [NextEditor](http://127.0.0.1:63320/node?ref=r%3A8d20232d-87e2-425b-b4d7-a9790e401b85%28de.slisson.mps.conditionalEditor.structure%29%2F2877762237607058140) to allow removing not needed editor hints. Could you please create a ticket in mps-extensions and reference your PR there?

2024-07-15 07:20 UTC, arimer approved these changes
Let's go 🚀

2024-07-15 07:32 UTC, merged