build: added publication to github packages
IETS3/iets3.opensource pull request #488
Opened 2021-06-24 14:29 UTC by arimer

This PR adds a publication to github packages for all artifacts.
In case we are building from CI and running on master/maintenance or a "mps" branch , TC will deploy all corresponding artifacts to github pages in addition to the nexus repository.

I've taken some inspiration from the PR provided for the mbeddr.platform publication: https://github.com/mbeddr/mbeddr.core/pull/2180

2021-06-24 15:18 UTC, sergej-koscejev commented on build.gradle
> +    /* this is pretty much a workaround so we don't need to change anything in Teamcity. Teamcity calls the  publishAllPublicationsToMavenRepository
This comment doesn't seem to apply to the iets3.opensource builds, they call `gradle publish` which should publish to all defined repositories.

2021-06-24 18:40 UTC, arimer commented on build.gradle
> +    /* this is pretty much a workaround so we don't need to change anything in Teamcity. Teamcity calls the  publishAllPublicationsToMavenRepository
I see. So just restricting the repository block to the correct branch, should be enough to allow publications for master/maintaines only.
Thx. for the hint.

2021-06-25 11:33 UTC, sergej-koscejev requested changes
Will approve after the unnecessary block is removed (or is confirmed to be in fact necessary).

2021-06-28 09:04 UTC, arimer commented on build.gradle
> +    /* this is pretty much a workaround so we don't need to change anything in Teamcity. Teamcity calls the  publishAllPublicationsToMavenRepository
You were right. TC is currently just running `build publish`. So we dont need this addition block here.

2021-06-28 09:07 UTC, arimer commented
@sergej-koscejev removed  unnecessary block.

2021-06-29 04:56 UTC, sergej-koscejev approved these changes

2021-06-30 12:39 UTC, merged