bugfix/fixDoubleMessages
IETS3/iets3.opensource pull request #489
Opened 2021-06-25 10:57 UTC by dbinkele

Each pull request should contain a brief summary of the proposed changes  
that can be easily read by the consumers of project releases.

Use the first comment in the pull request and update it as needed during
the work on pull request to keep the description up-to-date.

Some of the items in the description might include:

- compatibility issues with previous versions if this PR introduces any
breaking changes

- hints on the included migrations and things to consider when applying
the migration to the own project

- reference to a related Github issue

2021-06-28 19:45 UTC, wsafonov requested changes
- I'm curious, why did you change types in MessageBuffer? BL `set<>` looked totally valid and should work correctly, as soon as `equals`/`hashCode` contract is properly implemented
- first `if` in MessageUI.equals can be safely removed
- could you please give also a meaningful short title and a description to the PR? Unfortunately just following the issue doesn't enlight what is it all about.

2021-06-29 06:19 UTC, dbinkele commented
@wsafonov I implemented the changes ... have look once more please.

2021-06-30 13:13 UTC, dbinkele commented
@wsafonov Ticket is update with real cause for doubled messages in UI.

2021-07-01 13:30 UTC, wsafonov approved these changes

2021-07-01 15:14 UTC, merged