Improve type of box expression
IETS3/iets3.opensource pull request #514
Opened 2021-09-20 12:59 UTC by alexanderpann

When the expression in the box expression has a specific number type, a generic integer type is used instead. Fixes #170 
An example can be seen in #170. Let me know if you see any additional problems.

2021-09-25 18:59 UTC, AlexeiQ commented
Why is a copy of the type `valueType.copy` necessary here (and in the previous implementation)? I'm not questioning your implementation, that looks fine, but would like to know the reason for it/ when to use it.

2021-12-16 15:04 UTC, lhartl commented
@alexanderpann the ticket was updated. Please update the PR accordingly.

2021-12-16 16:27 UTC, lhartl requested changes
see comment above

2024-03-11 08:04 UTC, alexanderpann commented
@arimer I've added the requested warning. This PR could be merged.

2024-03-11 09:11 UTC, arimer commented
WIll check, thx.

2024-03-11 12:11 UTC, arimer approved these changes
New TS warning as suggested is added and tested 👍🏼

2024-03-11 12:32 UTC, lhartl approved these changes

2024-03-11 12:32 UTC, merged