Change StringLiteral constraint to not use regex
IETS3/iets3.opensource pull request #561
Opened 2022-04-07 08:35 UTC by alexanderpann

Regex is not used anymore to validate StringLiterals because long strings caused issues with nested regex expressions.
Fixes #545

2022-04-14 07:31 UTC, ftomassetti commented
It would be great to have this one merged and a release available :)

2022-04-21 06:14 UTC, ftomassetti commented
Is there anything that I can do to help here?

2022-04-25 11:12 UTC, lhartl requested changes
please check the reimplementation of the regex. E.g. \\" was not allowed in a string before, but is now.

2022-04-25 11:13 UTC, lhartl commented
@ftomassetti if you want to, of course, you can review PRs. Thank you for offering help!

2022-04-26 12:23 UTC, alexanderpann commented
> please check the reimplementation of the regex. E.g. \" was not allowed in a string before, but is now.

You are right that is was wrong but `\"` was allowed in the old implementation. What is not allowed is for example `\\"` because the backslash is escaped and not the quotation mark. I fixed this issue and checked some examples with the old and the new implementation and I think both implementation now behave the same.

2022-05-11 06:55 UTC, ftomassetti commented
Ok, it took me a while to get the project to open but I managed in the end :D
To me the PR looks good. I personally would find it slightly more clear changing the code from:
<img width="676" alt="Screenshot 2022-05-11 at 08 45 46" src="https://user-images.githubusercontent.com/439078/167787099-49fdb4df-69c5-4141-b4d4-20c3f56202ee.png">

Into:
<img width="624" alt="Screenshot 2022-05-11 at 08 46 34" src="https://user-images.githubusercontent.com/439078/167787129-b2c1b8be-2a1a-44ba-bb84-1273b17e6782.png">


But this is just a matter of taste. All in all it seems a working solution for an important problem, as having a StackOverflow for large strings is a real issue. So I would say it looks good!

2022-06-09 07:22 UTC, ftomassetti commented
Can I help getting this PR progressing? Should I open a PR based on this code but solving conflicts with master?

2022-06-14 11:28 UTC, lhartl approved these changes
Lgtm

2022-06-14 11:29 UTC, merged