Improve dark themes support for tables
IETS3/iets3.opensource pull request #625
Opened 2022-12-05 07:13 UTC by AlexeiQ

# What changed
- Tables `DataTable` now fully supports dark themes
  - Before (light + dark): 
<img src="https://user-images.githubusercontent.com/5792623/205460339-ae29dd2d-8f06-4d94-8e54-0af4463d86a1.png" width="300"> <img src="https://user-images.githubusercontent.com/5792623/205460312-a81ce8b7-96da-4941-bbb6-e15d811f9539.png" width="350">

  - Now (Darkula + High contrast, light stays the same): 
  <img src="https://user-images.githubusercontent.com/5792623/205460548-b2cd12fa-6d9f-4ef4-861f-e8e788053ddf.png" width="350"> <img src="https://user-images.githubusercontent.com/5792623/205460561-315d6697-d9aa-42a4-876e-18bfb7968188.png" width="350">

- Moved styles from inspector into dedicated stylesheet

# Todos
- [ ] Add change log entry (How to do this?)
- [ ] Add release comment

2022-12-05 17:11 UTC, AlexeiQ commented
Squashed, rebased onto `maintenance/mps20211` and resolved merge-conflicts

2023-01-26 15:31 UTC, arimer approved these changes
Changes look good to me 👍🏼 
Thanks for moving the styles into a seperate stylesheet :)

2023-02-10 11:59 UTC, wsafonov requested changes
- die Headern im Dark-Mode sind fast gar nicht von den normalen Zellen zu unterscheiden. Ich würde dann den Kontrast zwischen den beiden Kategorien von Zellen ähnlich wie im normalen Mode halten wollen. Vorschlag: die Werte im Dark auf 80 zu erhöhen.
- Tippfehler: `DataTableColumHeader` -> `DataTableColumnHeader`

2023-02-13 14:56 UTC, arimer commented
@wsafonov I've updated the colors to the suggested ones and fixed the typo:

<img width="1185" alt="grafik" src="https://user-images.githubusercontent.com/16648247/218491767-95a89bc9-9f20-416c-8323-f3d2b9abc750.png">

Give me a 👍🏼 on the comment and I merge this PR.

2023-02-13 14:58 UTC, wsafonov approved these changes

2023-02-13 15:08 UTC, merged