Add a cycle check to the unit definition + use correct conversion specifier when converting units
IETS3/iets3.opensource pull request #729
Opened 2023-11-27 09:22 UTC by alexanderpann

This PR fixes https://github.com/IETS3/iets3.opensource/issues/728. In addition, the automatically set conversion specifier of the `convert` expression and the `convertTo`  target is now used instead of the first applicable conversion specifier. This way, the converting even works with those cyclic definitions. The editor also shouldn't freeze anymore when using cyclic definitions. Example:
                      
```
quantity quantityA                                          
quantity quantityB                                          
                                                                               
unit a := b for quantityA
unit b := a for quantityB
unit c := c
                                                            
conversion a -> b {                                         
val as <no type> -> val * 1000                              
}                                                           
conversion b -> a {                                         
val as <no type> -> val / 1000                              
}                                                           

test case testConversionInterpreterCyclic [incomplete] {    
  assert convert[1 a -> b] equals 1000
  assert convert[1000 b -> a] equals 1
                                                            
  assert 5 a.convertTo(b)equals 5000
  assert 1000 b.convertTo(a)equals 1
}           
```

2023-11-27 11:24 UTC, HeikoBecker requested changes
Thank you for the work. The code itself looks fine.

But since the feature change is breaking, I would suggest the following:

- [x] recover the old behavior for the conversion specifiers
-  [ ] add an extension point that allows to configure which behavior is used (e.g. via a boolean flag)
- [ ] potentially show a warning that the old behavior is used 

This should make the code more robust in that existing developments (even though they relied on potentially buggy code) will not break.

2023-11-27 12:06 UTC, alexanderpann commented
I've enabled the new behavior for the tests which means that I had to add an extension to the test solutions. For KernelF tests, we don't have a good way to change extension points.

2023-11-28 07:20 UTC, alexanderpann commented
Not a breaking anymore since the old behavior was restored and you can now switch to the new behavior through the extension point

2023-11-28 10:57 UTC, HeikoBecker submitted a review, later dismissed
Changes look good to me now. The old behavior is preserved and the new behavior is easily accessible.

2023-11-29 10:19 UTC, HeikoBecker approved these changes
Thanks for the fix. With the new extension point there should not be a change in user-facing functionality.

2023-11-29 10:19 UTC, merged