build.gradle: added build fail on test failure
IETS3/iets3.opensource pull request #807
Opened 2024-02-29 21:18 UTC by arimer

At the moment our TC configuration allows the execution of the `publish` task despite of failing tests. This PR adds additional functionality to fail our build in case we have failing tests. 

We want to still execute all tests and collect their results as part of the junit result xml file. However in addition we want the build to fail in case tests are failing.  Therefore the `buildAndRunTests()` task was updated to parse the result xml file and throw an exception in case of test failures.

2024-02-29 21:19 UTC, arimer commented on build.gradle
> +        // evaluate junit result and fail on error
Tbh. I am not sure if we make this check only work in case we run on CI and not locally. Feedback is highly welcome here.

2024-02-29 21:24 UTC, alexanderpann commented on build.gradle
> +        // evaluate junit result and fail on error
Why should be there a difference when you run it locally? I am always in favor of the local and CI builds behaving the same way.

2024-02-29 23:36 UTC, sergej-koscejev commented
How about setting “halt on failure” to true in the MPS build scripts instead (on the ‘run tests from modules’)?

2024-03-01 17:40 UTC, alexanderpann commented
> How about setting “halt on failure” to true in the MPS build scripts instead (on the ‘run tests from modules’)?

With this setting, the build fails immediately when the first test fails. We want to run all tests and see what tests are failing, not only the first result.

2024-03-01 19:17 UTC, sergej-koscejev commented
> With this setting, the build fails immediately when the first test fails. We want to run all tests and see what tests are failing, not only the first result.

My experiments show that the build fails after the `<junit>` task but all tests in the test suite are run.

2024-03-05 07:29 UTC, arimer commented
> https://mps.builds.itemis.cloud/buildConfiguration/Iets3_BuildOrgIets3core/356044?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildDeploymentsSection=false&expandBuildTestsSection=true&expandBuildProblemsSection=true

Our TC behaviour is slightly different. All tests are executed until one failing test is detected. Afterwards the test execution of the remaining test is not done and those tests are does not end up in the junit xml file evaluated by TC.

Here an example of a build with `halt on failure` enabled.

https://mps.builds.itemis.cloud/buildConfiguration/Iets3_BuildOrgIets3core/356044?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildDeploymentsSection=false&expandBuildTestsSection=true&expandBuildProblemsSection=true

We have more then 5k tests, but only 3.2k tests were found.

2024-03-05 19:28 UTC, arimer commented on build.gradle
> +buildAndRunTests.configure { finalizedBy failOnTestError }
@sergej-koscejev as suggested I've added a finalizedBy dep. from our test task to a task failing the build. 

Pls. have a second look

2024-03-06 11:31 UTC, alexanderpann requested changes

2024-03-06 11:31 UTC, alexanderpann commented on build.gradle
> +buildAndRunTests.configure { finalizedBy failOnTestError }
Are you sure about the way to calculate the amount?  
[https://stackoverflow.com/a/30060286](https://stackoverflow.com/a/30060286) Testsuites contains the fields errors and failures and there is a separate error and failure element.

2024-03-06 11:58 UTC, arimer commented on build.gradle
> +buildAndRunTests.configure { finalizedBy failOnTestError }
Nice catch. I'd say catching for the xml elments names: `failure` and `error` (instead of the plural with `s`) should do the trick. What do you to think?

2024-03-07 09:13 UTC, arimer commented
@alexanderpann do you want  to have a second look?

2024-03-07 13:22 UTC, alexanderpann approved these changes
I'll approve but can you run it locally and make a few tests fail to check if the numbers line up?

2024-03-07 16:12 UTC, arimer commented
@alexanderpann of course.

2024-03-07 19:14 UTC, merged