Bugfix/type system improvement
IETS3/iets3.opensource pull request #872
Opened 2024-03-21 13:34 UTC by mgronover

Issues: #505 and #848

EmptyType is deleted from the list of types of a JoinType, if there is at least one other type.
The list of types of a JoinType is now sorted lexical. So there is no difference in the order of given of types within a  JoinType.

2024-03-22 07:42 UTC, HeikoBecker requested changes
Somehow the version of com.mbeddr.mpsutil.blutil is downgraded for org.iets3.core.base. Can you please try reverting this change?

Other then that, the changes look good to me.

2024-03-25 07:25 UTC, HeikoBecker approved these changes
Thanks for the fix!

LGTM

2024-03-25 07:44 UTC, merged

2024-03-25 09:03 UTC, arimer commented
Just for my understanding, why do we need to [sort](http://127.0.0.1:63320/node?ref=r%3A5bf19129-2710-45a6-906e-9ee2d0977853%28org.iets3.core.expr.simpleTypes.plugin%29%2F8126947098204166783) the types list?

2024-03-25 09:06 UTC, arimer commented
@mgronover do you mind closing the issues in case your chages fix the bugs?

2024-03-25 14:37 UTC, HeikoBecker commented
> Just for my understanding, why do we need to [sort](http://127.0.0.1:63320/node?ref=r%3A5bf19129-2710-45a6-906e-9ee2d0977853%28org.iets3.core.expr.simpleTypes.plugin%29%2F8126947098204166783) the types list?

See the last comment by Klaus on https://github.com/IETS3/iets3.opensource/issues/505.

The idea was to allow join types to not be bound to the structure of the alt expression, i.e., both 
```
alt [
  x ==1 => 1
  x ==2 => true
  ]
 ```
 
 ```
alt [
 x == 2 => true
  x == 1 => 1
  ]
  ```
  
are typesystem-equivalent