Bugfixes and improvements for tew unit language
IETS3/iets3.opensource pull request #934
Opened 2024-04-29 05:26 UTC by alexanderpann

- small fixes related to the minimization of groups
- exponent expression now doesn't use references as the base anymore
- improvement and fixes in substitute menus
- small adaptions to the standard libraries
- improvements in the NewUnitLanguageMigrationHelper to support migrating custom libraries

The only bug that I really don't understand is how the message "Can' find original node" in the [GroupHelper](http://127.0.0.1:63320/node?ref=r%3Ad4f1532d-fc5c-419f-84ee-daef42867c8e%28org.iets3.core.expr.typetags.physunits.typesystem%29%2F7448342049581699876) class can happen.

2024-05-02 06:36 UTC, HeikoBecker requested changes
Thanks for the bugfixes!

Some questions from the review:

- [ ] Why is it necessary to hardcode these references here? (Also the later ones further down)
![image](https://github.com/IETS3/iets3.opensource/assets/3237993/b2cbca2a-b6c4-4f79-915c-41394def851c)

The comment does not make it all that clear to me.

- [ ] Why was the sorting at the end removed in `sortByExponent`?
![image](https://github.com/IETS3/iets3.opensource/assets/3237993/3bd8e4ab-5311-42ba-b6e7-882176c5e88e)

2024-05-02 11:52 UTC, alexanderpann commented
> Why is it necessary to hardcode these references here?
This is explained in the comment: There would be a cyclic dependency between `org.iets3.core.expr.typetags.units.si` and `org.iets3.core.expr.typetags.units.si` which is disallowed in the IETS3 build script (http://127.0.0.1:63320/node?ref=r%3Ac3d6ae0c-8b10-477f-a3e9-5dc8700ceb13%28org.iets3.opensource.build.build%29%2F4699376143909127101).

> Why was the sorting at the end removed in sortByExponent
It didn't fully work and it seems to me that we are dealing with only multiplications at the point, so I recreated the multiplications from the sorted nodes. I have to admit that I didn't test the code when we have the reduction set to fractions.

2024-05-07 13:20 UTC, psuzzi approved these changes
Premise: We define [Quantity](http://127.0.0.1:63320/node?ref=r%3A4f64e2f0-6a4e-4db3-b3bf-7977f44949b6%28org.iets3.core.expr.typetags.physunits.structure%29%2F2034036099103723287) by its name and symbol, and [Unit](http://127.0.0.1:63320/node?ref=r%3A4f64e2f0-6a4e-4db3-b3bf-7977f44949b6%28org.iets3.core.expr.typetags.physunits.structure%29%2F8337440621611267903) by its definition, each referring to a specification. It's crucial that the specifications of Unit and Quantity align. All expressions are simplified to SI-based equivalents, as visible in the inspector.
![image](https://github.com/IETS3/iets3.opensource/assets/352831/c50bb62a-88e3-407f-86d7-7ee7a320de67)


This pull request introduces several improvements and bug fixes to Units, Quantities, and associated elements, including editors, behaviors, presentations, type systems, and migrations. Key enhancements include:

- Integration of qualified names for Units, and the adoption of symbols in the getName method for Quantities.
- Corrections in the multiplication, division and exponentiation of Quantities for derived units.
- [GroupHelper](http://127.0.0.1:63320/node?ref=r%3Ad4f1532d-fc5c-419f-84ee-daef42867c8e%28org.iets3.core.expr.typetags.physunits.typesystem%29%2F4704593238063114735) is a central and complex class, and the changes on it play a significant role in implementing these improvements and bug fixes.
- support data information prefixes (eg KiBi as opposite of Kg)
- Test improvements
- and much more..

Modifications to [SIBaseUnits](http://127.0.0.1:63320/node?ref=r%3A4134cae9-4017-4808-bf1c-768cb21cb9ea%28org.iets3.core.expr.typetags.phyunits.si.units%29%2F4067340399592148752) and [SIDerivedUnits](http://127.0.0.1:63320/node?ref=r%3A4134cae9-4017-4808-bf1c-768cb21cb9ea%28org.iets3.core.expr.typetags.phyunits.si.units%29%2F4067340399592148770) have also been made to ensure the representation is coherent with the literature.

Additionally, the documentation has been significantly enhanced and is made available on the [Platform Docs > Physical Units Language webpage](http://mbeddr.com/mps-platform-docs/languages/kernelf/tour/solutions/KernelFTour/screenshots/PhysicalUnitsLanguage/PhysicalUnitsLanguage/), such that it can be directly referenced also outside of the codebase.

All the changes looks good to me. I have to say this is a really good example of readable PR!

2024-05-08 06:28 UTC, HeikoBecker approved these changes
Thanks for the fixes!

LGTM.

2024-05-08 11:09 UTC, merged